(set-option :print-success false)
(set-logic QF_UF)
(set-option :sat.euf true)
(set-option :tactic.default_tactic smt)
(set-option :solver.proof.log LevelCrossing_p_inv_base.smt2)
(declare-const vBarriersDown_0 Bool)
(declare-const vCarsCrossing_1 Bool)
(declare-const vTrainApproach_0 Bool)
(declare-const vLightsFlash_0 Bool)
(declare-const vTrainPassed_0 Bool)
(declare-const vLightsFlash_1 Bool)
(declare-const vBarriersDown_1 Bool)
(declare-const vWhiteLight_1 Bool)
(declare-const vWhiteLight_0 Bool)
(declare-const vTrainCrossing_1 Bool)
(declare-const vCarsCrossing_0 Bool)
(declare-const vTrainCrossing_0 Bool)
(assert(= vBarriersDown_0 false))
(assert(= vCarsCrossing_1 false))
(assert(= vTrainApproach_0 false))
(assert(= vLightsFlash_0 false))
(assert(= vTrainPassed_0 false))
(assert(= vLightsFlash_1 false))
(assert(= vBarriersDown_1 false))
(assert(= vWhiteLight_1 false))
(assert(= vWhiteLight_0 false))
(assert(= vTrainCrossing_1 false))
(assert(= vCarsCrossing_0 false))
(assert(= vTrainCrossing_0 false))
(assert (not (not (or (and (not vBarriersDown_0) vWhiteLight_0) (and vCarsCrossing_0 vTrainCrossing_0)))))
(check-sat)
(exit)
